[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.copy]
target = "main.lua"
position = "append"
sources = ["palette.lua"]

[[patches]]
[patches.module]
source = "localization/en-us.lua"
before = "main.lua"
name = "palette/localization/en-us"

[[patches]]
[patches.module]
source = "utils.lua"
before = "main.lua"
name = "palette/utils"

[[patches]]
[patches.module]
source = "trance/core.lua"
before = "main.lua"
name = "palette/trance/core"
[[patches]]
[patches.module]
source = "trance/ui.lua"
before = "main.lua"
name = "palette/trance/ui"